### PR TITLE
Update API

### LINKED ISSUE #131: HTTP 426: Upgrade required
**Describe the bug**
I just received this error when opening a program that was saved as a favorite.
But I seem to get it now on every request.

**Expected behavior**
It works as before.

**Screenshots**
```
2020-01-23 00:56:24.236 T:1290826624   ERROR: GetDirectory - Error getting plugin://plugin.video.vtm.go/catalog
2020-01-23 00:56:24.240 T:1937588800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/catalog) failed
2020-01-23 00:56:26.869 T:1257255808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Error 426.
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/plugin.py", line 8, in <module>
                                                plugin.run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 193, in run
                                                routing.run(params)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 25, in show_channels
                                                Channels(kodi).show_channels()
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/channels.py", line 28, in show_channels
                                                channel_infos = self._vtm_go.get_live_channels()
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py", line 380, in get_live_channels
                                                response = self._get_url('/%s/live' % self._mode())
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py", line 679, in _get_url
                                                raise Exception('Error %s.' % response.status_code)
                                            Exception: Error 426.
                                            -->End of Python script error report<--
2020-01-23 00:56:27.082 T:1290826624   ERROR: GetDirectory - Error getting plugin://plugin.video.vtm.go/channels
2020-01-23 00:56:27.086 T:1937588800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/channels) failed
```

**System**
 - Addon version: 0.9.2
 - Kodi version: 18.5
 - Inputstream adaptive version: 2.4.2
 - Operating System: (Windows / Mac OS / Android / LibreElec / OSMC / ...) LibreELEC v9.2.0
 - Special Hardware: (RPI / Vero4K+ / ...) RPI3

### PR DESCRIPTION
**Pull request by michaelarnauts**
Fixes #131, #129 

This pull request updates the API so it works again. This caused a few changes:
* Kids mode is now replaced by profiles
* The API to get a single episode is gone, so some views might contain empty plots. This could be improved in the future by using `get_program` and filtering out the episode ourselves.

Note that these changes are still rough around the edges.

### CODE REVIEW

**Comment by michaelarnauts** [comment]
@dagwieers feel free to do some testing :)

**Comment by michaelarnauts** [comment]
The tests seems to be failing only for Python 2.7, but I'm not sure why.

**Comment by dagwieers** [comment]
Yesterday, the SD card of mij test system failed, so I need to rebuild it and I cannot find my box with micro SD cards right now. Bad timing 😕

**Comment by michaelarnauts** [comment]
Allright, all is green again. I'll merge this so master isn't broken anymore.

**Pull request merged**
