### PR TITLE
fix sanity warnings

### PR DESCRIPTION
**Pull request by mediaminister**
Fix sanity warnings, following PEP 8 style

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Thanks!

I'm wondering if that `channel = os.path.basename(channel_url).split('-')[0],` actually worked, since the channel will be a list, right?

**Comment by mediaminister** [comment]
No, the channel is a simple string, it stores only the first item of the list containing the splitted parts.

**Comment by michaelarnauts** [comment]
Sure, that is what should happen, but doesnt the comma at the end (what you removed in this pr) turn it into a list? Therefore, I don't know how this could have worked. :)

**Comment by mediaminister** [comment]
There is definitely a chance it worked, it wouldn't surprise me if Kodi converted this list to a string.
But I think the comma was a typo. @dagwieers can confirm what the comma was all about. :)

**Pull request merged**
