### PR TITLE
Increase coverage, remove dead code

### PR DESCRIPTION
**Pull request by dagwieers**
Various functions are not used, or is duplicate code.
They can be reintroduced when we actually need them.

### CODE REVIEW

**Comment by dagwieers** [comment]
This is ready to be merged. Beware that it disables a test causing #65

**Comment by michaelarnauts** [comment]
@dagwieers I'm not sure if I afree with the removal of the functions in the kodiutils.

I understand your desire to have a high coverage, and I fully support this, but I think we should exclude the kodi* functions from code coverage. They exist to ease the development, and are not really part of the addon in my opinion.

**Comment by dagwieers** [comment]
They don't ease the development if they are not being used.
It is easy to add them again when they are needed.
But since kodiutils is code we manage as part of the project it is part of what we cover during testing.
If you would exclude this, we have a narrow view of what is being tested.

**Comment by michaelarnauts** [comment]
They ease the development when we're adding new features, and we want to use some of these functions. I agree they can be added again, but for me, this is more like boilerplate code that every plugin should have, and ideally should be in another repo.

I'm not a seasoned python dev, and things like autocomplete help me a lot to get things done, and I don't like to copy a function from vrt.nu for example every time I want to do something with Kodi.

I don't see the issue if these functions are excluded from the coverage.

**Pull request merged**
