### PR TITLE
Add support for vtm go kids mode

### PR DESCRIPTION
**Pull request by michaelarnauts**

### CODE REVIEW

**Comment by michaelarnauts** [comment]
@dagwieers what do you think?
I like the ability to quickly switch from within the addon. I still have the problem that if you bookmark a program or category from within the kids mode, that bookmark will not work when switched back to normal mode since the mode isn't in the url. That will probably have to change.

**Comment by michaelarnauts** [comment]
Things I want to improve:
* Hide the kids mode setting
* Put kids-mode in url somehow so bookmarks work

**Comment by dagwieers** [comment]
I think the Kids Zone should just be an entry in the main menu.

**Comment by michaelarnauts** [comment]
It's a combination of a entry in the main menu, and a setting. This mimics how the app behaves.

By default, you open the addon in normal mode, but you have an entry to enable the kids mode. In kids mode, you haven an entry to disable kids mode (switch back to normal mode).
This mode is saved in a setting so you go back to your last used mode.

This setting is only used for the main menu. As soon as you open a submenu (a-z, catalog, live tv, ...) the mode is added to the url so you can bookmark this.

The one thing I can't find how to do this nicely is to make it more clear that kids mode is active. Currently, only the option to disable the kids mode tells you that you are in kids mode. I was thinking to append ` (Kids Mode)` or something after the menu items, but that's a bit overkill imo. Maybe something added to the plot descriptions of the main menu items... Not sure...

**Comment by michaelarnauts** [comment]
I'm quite happy with how it works now.

**Comment by dagwieers** [comment]
I don't like the "Enable/Disable Kids mode" menu item.

IMO the Kids Zone should just be a submenu of the main-menu, with the same options as the main-menu. It shouldn't be an action on the main-menu. (Which in fact doesn't seem to work currently, because you have to exit the add-on and re-enter in order to make it effective).

Then the only option in the settings you may want is to enforce the Kids Zone, make it available in the main-menu (default) or disable it.

**Comment by michaelarnauts** [comment]
I don't notice that big here. It refreshes the view and the mode is switched.

I also thought about your suggestion, and I would fully agree if the kids mode (it's not a zone) contained content that wasn't available in the normal mode.

Instead, everything in the kids mode is also in the normal mode, so it just is a subset of the library aimed at children. You could look at it like a kind of filter that you activatie.

I'm not 100% convinced what I have now is the right way, it's just what I had in mind and resembled the mobile app.

**Comment by dagwieers** [comment]
Every menu in the main-menu (apart from A-Z) is a subset (or a view) of the full A-Z listing. So in that regard the Kids Zone is not different from Catalogue/Kids, except that you have different views in that subset.

So it acts more like our "My programs" section in VRT NU.

That is also why I call it a Kids Zone, rather than a Kids mode, as IMO it is much easier to integrate in Kodi's interface. The "Enable/Disable Kids mode" is a questionable user interface from that perspective. People don't expect a switch in that menu that influences this menu.

I understand your desire to stick to the original as much as possible, but in this case I wouldn't do it for the user-interface. Functionally, things look/work fine. If you like I can implement my proposal for the Kids Zone and we can re-evaluate?

**Pull request merged**
