### PR TITLE
Uniformise travis and local checking flow

### PR DESCRIPTION
**Pull request by michaelarnauts**
I don't like the way we duplicate the travis checks, and the same checks for local development. In other projects, I'm used to having the following commands for local development:

* `make clean`
  * remove temp files that could interfere
* `make check`
  * runs all code checks (linter, common errors, translations, ...). Individual checks are available as `make check-*`
* `make test`
  * run all unit and acceptance tests
* `make build`
  * package the project

I will also clean up the build output. It's hard to find the context when a test has failed.

### CODE REVIEW

**Comment by dagwieers** [comment]
You may be standardizing with how you do it at work, but it becomes inconsistent with the other Kodi projects we have. And there's some benefit in keeping things in sync IMO.

**Comment by michaelarnauts** [comment]
The only difference will be the Travis file, and the Makefile. IMO it's a lot cleaner since the commands now match. There is no lost functionality and no need to keep local tests and Travis tests synchronized.

**Comment by michaelarnauts** [comment]
This change also fixes:
* locally testing on python 3.7
* clear up some errors from `kodi-addon-checker`

**Comment by dagwieers** [comment]
Sure, but `make sanity` or `make zip` no longer work.
The Makefile was identical to the other projects.
You made things convenient, only for yourself.
With no real benefit to others.

**Comment by michaelarnauts** [comment]
It's now make check and make build that do exactly the same. Actually, those commands are more common in other projects.

Also, Travis now uses the same commands.

**Pull request merged**
