### PR TITLE
Rework Kids zone

### PR DESCRIPTION
**Pull request by dagwieers**
This makes the Kids zone part of the routing.

### CODE REVIEW

**Comment by dagwieers** [comment]
This needs a bit more work, I would rather have a single settings:
- **Kids zone:**  [ Disable | **Enable** | Force ]

Rather than:
- **Enable Kids Zone:**  [ **True** | False ]
  - **Force Kids Zone:**  [ True | **False** ]

**Comment by dagwieers** [comment]
I also need to investigate if Kids zone has its own search functionality.

And for the breadcrumbs (that are now implemented for Kids zone) it is not inherited to routes that don't have a kids-variant (like */program* or */movie*). Not sure if that is needed or not.

**Comment by michaelarnauts** [comment]
Kids zone does have a different search endpoint. The results are filtered.

**Comment by dagwieers** [comment]
Ok, I fixed that as well.

**Comment by dagwieers** [comment]
Voor mij is dit klaar. Als er een beslissing is over de settings, dan kunnen we dat achteraf aanpassen.

**Comment by michaelarnauts** [comment]
Thanks!

**Pull request merged**
